# @format

name: Lint

on: [push, pull_request]
with:
    src: "./ckanext/scryfall/plugin.y"

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: psf/black@stable
